# Generated by Django 4.1.7 on 2023-03-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
