# Generated by Django 4.1.7 on 2023-03-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0003_remove_card_last_check_in_card_last_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='last_check',
            new_name='last_check_in',
        ),
    ]
