# Generated by Django 4.1.7 on 2023-03-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0004_rename_last_check_card_last_check_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_check_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
