# Generated by Django 4.1.7 on 2023-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0006_station_cardregistries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
