# Generated by Django 4.1.7 on 2023-03-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0007_alter_station_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardregistries',
            name='timestamp',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
