# Generated by Django 3.2.8 on 2023-07-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0008_alter_cardregistries_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='owner_full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
