# Generated by Django 3.2.8 on 2023-07-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0009_alter_card_owner_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='physical_card_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
