# Generated by Django 3.2.8 on 2023-07-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0011_station_is_waiting_for_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='card_to_pair_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='card_api.card'),
        ),
    ]
