# Generated by Django 3.2.8 on 2023-08-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0012_station_card_to_pair_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardregistries',
            name='checkin_or_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
