# Generated by Django 3.2.8 on 2023-08-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_api', '0015_remove_cardregistries_checkin_or_checkout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardregistries',
            options={'verbose_name_plural': 'CardRegistries'},
        ),
    ]
